// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOnfD9R-wBkpMlrv_c9RQoJMAUH5pQvyU',
    appId: '1:104173808393:web:56c2e6715ea9339e80c1d8',
    messagingSenderId: '104173808393',
    projectId: 'fb-chatapp-acfb4',
    authDomain: 'fb-chatapp-acfb4.firebaseapp.com',
    storageBucket: 'fb-chatapp-acfb4.appspot.com',
    measurementId: 'G-C8CSFZSPKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWyJqCCzlDDoDvlydRUls8bOmJW1xDg_Q',
    appId: '1:104173808393:android:5228678580f6e37c80c1d8',
    messagingSenderId: '104173808393',
    projectId: 'fb-chatapp-acfb4',
    storageBucket: 'fb-chatapp-acfb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBZMcown4u5uIkQEzZEEi30lgB-u_a9Q',
    appId: '1:104173808393:ios:ffd05904b708b7ec80c1d8',
    messagingSenderId: '104173808393',
    projectId: 'fb-chatapp-acfb4',
    storageBucket: 'fb-chatapp-acfb4.appspot.com',
    iosBundleId: 'com.example.fbChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBZMcown4u5uIkQEzZEEi30lgB-u_a9Q',
    appId: '1:104173808393:ios:ffd05904b708b7ec80c1d8',
    messagingSenderId: '104173808393',
    projectId: 'fb-chatapp-acfb4',
    storageBucket: 'fb-chatapp-acfb4.appspot.com',
    iosBundleId: 'com.example.fbChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOnfD9R-wBkpMlrv_c9RQoJMAUH5pQvyU',
    appId: '1:104173808393:web:cd5f880754cd44c380c1d8',
    messagingSenderId: '104173808393',
    projectId: 'fb-chatapp-acfb4',
    authDomain: 'fb-chatapp-acfb4.firebaseapp.com',
    storageBucket: 'fb-chatapp-acfb4.appspot.com',
    measurementId: 'G-3V0EQRCRMP',
  );
}
